name: 'ga4'
version: '0.1.4'
config-version: 2
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# The following variables should be set in the project that loads this package. 
vars:
    project: "turbo-ukr"
    dataset: "analytics_286195171"
    start_date: "20220704" # Defines the earliest GA4 event _TABLE_SUFFIX to load into base events model.
    frequency: daily
    today_and_yesterday : [
        current_date()
        , date_sub(current_date(), interval 1 day)
    ]
    today_and_last_week : [
        current_date()
        , date_sub(current_date(), interval 1 day)
        , date_sub(current_date(), interval 2 day)
        , date_sub(current_date(), interval 3 day)
        , date_sub(current_date(), interval 4 day)
        , date_sub(current_date(), interval 5 day)
        , date_sub(current_date(), interval 6 day)
        , date_sub(current_date(), interval 7 day)
    ]

models:
  ga4:
    +materialized: view
    marts:
      +materialized: table
    staging:
      ads_data:
        +materialized: incremental
      rawdata:
        +materialized: table